/* 

10. Implement a method that takes a List of Integers and returns the highest and lowest numbers.
📌 Task: Use List.sort() or iterate manually to find max/min values.

 */

public class FindNumbers {

    public static Integer findMax(List<Integer> numbers) {
        number.sort();
        return numbers[number.size() - 1];
    }

    public static Integer findMin(List<Integer> numbers) {
        number.sort();
        return numbers[0];
    }

}

